name = "thcs-chaodau"
main = "src/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "duongminhchau"
database_id = "259c6a40-dc67-4733-859b-abcd1d67a6cb"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "chaodau-files"
preview_bucket_name = "chaodau-files-dev"

[assets]
directory = "./public"
binding = "ASSETS"

[vars]
ADMIN_USER = "admin"
ADMIN_PASS = "admin123"
JWT_SECRET = "doi_thanh_chuoi_bi_mat_that_dai_va_kho_doan_1234567890"
